FROM python:3.7-alpine
WORKDIR /app
RUN apk add --update --no-cache g++ gcc libxslt-dev
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
ENV PYTHONPATH /app
CMD ["python", "tests.py"]